export declare const ERROR_MESSAGES: {
    readonly NO_TOKEN: "Access denied. No token provided.";
    readonly INVALID_TOKEN: "Invalid or expired token.";
    readonly INVALID_ROLE: "Invalid user role.";
    readonly ACCESS_DENIED: "Access denied. Insufficient permissions.";
    readonly USER_NOT_FOUND: "User not found.";
    readonly ACCOUNT_INACTIVE: "Your account is inactive. Please contact support.";
    readonly EMAIL_NOT_VERIFIED: "Please verify your email address.";
    readonly PHONE_NOT_VERIFIED: "Please verify your phone number.";
    readonly INVALID_CREDENTIALS: "Invalid email/phone or password.";
    readonly ACCOUNT_LOCKED: "Account is temporarily locked. Try again later.";
    readonly SESSION_EXPIRED: "Session expired. Please try again.";
    readonly MAX_ATTEMPTS_EXCEEDED: "Maximum attempts exceeded. Please request new OTP.";
    readonly FILE_UPLOAD_FAILED: "File upload failed";
    readonly INVALID_FILE_TYPE: "Invalid file type. Allowed: JPEG, PNG, JPG, WebP, GIF, SVG";
    readonly FILE_TOO_LARGE: "File size too large. Maximum size: 10MB";
    readonly FILE_NOT_FOUND_IN_S3: "File not found in storage";
    readonly S3_CONFIGURATION_ERROR: "S3 storage not configured properly";
    readonly PRESIGNED_URL_GENERATION_FAILED: "Failed to generate upload URL";
    readonly BULK_UPLOAD_LIMIT_EXCEEDED: "Maximum 10 files allowed per bulk upload";
    readonly FILE_VALIDATION_FAILED: "File validation failed";
    readonly IMAGE_FOLDER_INVALID: "Image must be in category-images folder";
    readonly ORPHANED_IMAGES_CLEANUP_FAILED: "Failed to cleanup orphaned images";
    readonly VALIDATION_ERROR: "Validation failed.";
    readonly INVALID_EMAIL: "Invalid email format.";
    readonly INVALID_PHONE: "Invalid phone number. Must be 10 digits.";
    readonly INVALID_PASSWORD: "Password must be at least 6 characters.";
    readonly PASSWORDS_DONT_MATCH: "Passwords do not match.";
    readonly INVALID_NAME: "Name must be between 2 and 50 characters.";
    readonly INVALID_GENDER: "Gender must be male, female, or other.";
    readonly INVALID_DATE: "Invalid date format. Use YYYY-MM-DD.";
    readonly INVALID_OTP: "Invalid or expired OTP.";
    readonly INVALID_SESSION_ID: "Invalid session ID.";
    readonly IDENTIFIER_REQUIRED: "Email or phone is required.";
    readonly INVALID_IDENTIFIER: "Please enter a valid email or 10-digit phone number.";
    readonly INVALID_TYPE: "Invalid type. Must be register, login, or forgot_password.";
    readonly USER_DATA_INVALID: "userData must be an object.";
    readonly SESSION_ID_REQUIRED: "Session ID is required.";
    readonly OTP_REQUIRED: "OTP is required.";
    readonly OTP_INVALID_FORMAT: "OTP must be exactly 6 digits.";
    readonly OTP_NUMERIC: "OTP must contain only numbers.";
    readonly NAME_REQUIRED: "Name is required.";
    readonly PASSWORD_REQUIRED: "Password is required.";
    readonly PASSWORD_EMPTY: "Password cannot be empty.";
    readonly CONFIRM_PASSWORD_REQUIRED: "Confirm password is required.";
    readonly EMAIL_REQUIRED: "Email is required.";
    readonly GENDER_INVALID: "Gender must be male, female, or other.";
    readonly DATE_FORMAT_INVALID: "Invalid date format. Use YYYY-MM-DD.";
    readonly EMAIL_ALREADY_REGISTERED: "Email already registered";
    readonly PHONE_ALREADY_REGISTERED: "Phone number already registered";
    readonly INVALID_SESSION_TYPE_REGISTER: "Invalid session type for registration";
    readonly INVALID_SESSION_TYPE_PASSWORD_RESET: "Invalid session type for password reset";
    readonly SESSION_EXPIRED_NOT_VERIFIED: "Session expired or not verified";
    readonly REGISTRATION_IDENTIFIER_MISMATCH: "Registration identifier must match the identifier used for OTP verification";
    readonly PASSWORD_PREPARATION_FAILED: "Password validation failed";
    readonly PASSWORD_RESET_FAILED: "Password reset failed";
    readonly FORGOT_PASSWORD_OTP_MESSAGE: "If your account exists, you will receive an OTP.";
    readonly ACCOUNT_DEACTIVATED: "Account is deactivated. Please contact support.";
    readonly ACCOUNT_NOT_VERIFIED: "Account not verified. Please verify your account.";
    readonly NO_PASSWORD_FIELD: "No password field found in user object";
    readonly PASSWORD_NOT_HASHED: "Password not properly hashed";
    readonly NOT_FOUND: "Resource not found.";
    readonly ALREADY_EXISTS: "Resource already exists.";
    readonly INVALID_OBJECT_ID: "Invalid MongoDB ObjectId";
    readonly EMPTY_ARRAY_NOT_ALLOWED: "Array cannot be empty";
    readonly REQUIRED_PARAM_MISSING: "Required parameter is missing";
    readonly INVALID_PAGINATION_PARAMS: "Invalid pagination parameters";
    readonly CART_EMPTY: "Cart is empty.";
    readonly INVALID_QUANTITY: "Invalid quantity.";
    readonly ORDER_CANCELLED: "Order has been cancelled.";
    readonly SERVER_ERROR: "Internal server error.";
    readonly DATABASE_ERROR: "Database connection error.";
    readonly UPLOAD_ERROR: "File upload failed.";
    readonly EMAIL_SEND_ERROR: "Failed to send email.";
    readonly SMS_SEND_ERROR: "Failed to send SMS.";
    readonly AWS_S3_ERROR: "AWS S3 service error";
    readonly MONGOOSE_ERROR: "Database operation failed";
    readonly VALIDATION_MIDDLEWARE_ERROR: "Validation middleware error";
    readonly TOO_MANY_REQUESTS: "Too many requests. Please try again later.";
    readonly OPERATION_NOT_ALLOWED: "Operation not allowed";
    readonly INSUFFICIENT_PERMISSIONS: "Insufficient permissions for this operation";
    readonly FEATURE_NOT_IMPLEMENTED: "Feature not implemented yet";
    readonly SERVICE_UNAVAILABLE: "Service temporarily unavailable";
    readonly INVALID_SLUG_FORMAT: "Slug can only contain lowercase letters, numbers, and hyphens";
    readonly INVALID_BOOLEAN_VALUE: "Value must be true or false";
    readonly INVALID_NUMBER: "Invalid number format";
    readonly INVALID_ARRAY: "Invalid array format";
    readonly STRING_LENGTH_EXCEEDED: "String length exceeded maximum limit";
    readonly INVALID_URL_FORMAT: "Invalid URL format";
};
export declare const SUCCESS_MESSAGES: {
    readonly LOGIN_SUCCESS: "Login successful.";
    readonly REGISTER_SUCCESS: "Registration successful.";
    readonly LOGOUT_SUCCESS: "Logout successful.";
    readonly PASSWORD_RESET: "Password reset successful.";
    readonly EMAIL_VERIFIED: "Email verified successfully.";
    readonly PHONE_VERIFIED: "Phone verified successfully.";
    readonly PROFILE_UPDATED: "Profile updated successfully.";
    readonly OTP_SENT: "OTP sent successfully.";
    readonly OTP_VERIFIED: "OTP verified successfully.";
    readonly OTP_GENERATED_DEV: "OTP generated successfully (check server console)";
    readonly OTP_EMAIL_SENT: "OTP sent to your email";
    readonly OTP_EMAIL_ISSUE: "OTP generated (email service issue)";
    readonly OTP_SMS_NOT_CONFIGURED: "OTP would be sent to your phone (SMS service not configured)";
    readonly OTP_VERIFIED_DEV: "OTP verified successfully (Development Mode)";
    readonly WELCOME_EMAIL_SENT: "Welcome email sent";
    readonly TEST_USER_CREATED: "Test user created for development";
    readonly PASSWORD_UPDATED_RELOGIN: "Password updated. Please try login again.";
    readonly PASSWORD_REHASHED: "Password re-hashed and saved";
    readonly USER_REGISTERED_SUCCESS: "User registered successfully";
    readonly UPLOAD_URL_GENERATED: "Upload URL generated successfully";
    readonly BULK_UPLOAD_URLS_GENERATED: "Bulk upload URLs generated successfully";
    readonly IMAGE_UPLOADED: "Image uploaded successfully";
    readonly IMAGE_VALIDATED: "Image validated successfully";
    readonly IMAGE_INFO_FETCHED: "Image information fetched successfully";
    readonly IMAGE_DELETED: "Image deleted successfully";
    readonly S3_FILE_INFO_FETCHED: "File information fetched successfully";
    readonly PRESIGNED_URL_CREATED: "Presigned URL created successfully";
    readonly DOWNLOAD_URL_GENERATED: "Download URL generated successfully";
    readonly VIEW_URL_GENERATED: "View URL generated successfully";
    readonly FILE_EXISTS_CHECKED: "File existence checked successfully";
    readonly S3_OPERATION_SUCCESS: "S3 operation completed successfully";
    readonly SERVICE_ADDED: "Service created successfully";
    readonly SERVICE_UPDATED: "Service updated successfully.";
    readonly SERVICE_DELETED: "Service deleted successfully.";
    readonly SERVICE_FETCHED: "Service fetched successfully";
    readonly ADDED_TO_CART: "Product added to cart.";
    readonly CART_UPDATED: "Cart updated successfully.";
    readonly CART_CLEARED: "Cart cleared successfully.";
    readonly CART_FETCHED: "Cart fetched successfully";
    readonly ORDER_PLACED: "Order placed successfully.";
    readonly ORDER_UPDATED: "Order updated successfully.";
    readonly ORDER_CANCELLED: "Order cancelled successfully.";
    readonly ORDER_FETCHED: "Order fetched successfully";
    readonly ORDERS_FETCHED: "Orders fetched successfully";
    readonly REVIEW_ADDED: "Review added successfully.";
    readonly REVIEW_UPDATED: "Review updated successfully.";
    readonly REVIEW_DELETED: "Review deleted successfully.";
    readonly REVIEWS_FETCHED: "Reviews fetched successfully";
    readonly OPERATION_SUCCESS: "Operation completed successfully";
    readonly DATA_FETCHED: "Data fetched successfully";
    readonly DATA_UPDATED: "Data updated successfully";
    readonly DATA_DELETED: "Data deleted successfully";
    readonly DATA_CREATED: "Data created successfully";
    readonly BULK_OPERATION_SUCCESS: "Bulk operation completed successfully";
    readonly VALIDATION_SUCCESS: "Validation passed successfully";
    readonly HEALTH_CHECK_OK: "Service is operational";
    readonly CONFIGURATION_VALID: "Configuration is valid";
    readonly SETTINGS_UPDATED: "Settings updated successfully";
    readonly CACHE_CLEARED: "Cache cleared successfully";
    readonly PAGINATED_DATA_FETCHED: "Paginated data fetched successfully";
    readonly SYSTEM_HEALTHY: "System is healthy";
    readonly SERVICE_RUNNING: "Service is running normally";
    readonly BACKUP_CREATED: "Backup created successfully";
    readonly MAINTENANCE_COMPLETED: "Maintenance completed successfully";
    readonly API_REQUEST_SUCCESS: "API request successful";
    readonly WEBHOOK_RECEIVED: "Webhook received successfully";
    readonly INTEGRATION_SUCCESS: "Integration completed successfully";
    readonly NOTIFICATION_SENT: "Notification sent successfully";
    readonly EMAIL_SENT: "Email sent successfully";
    readonly SMS_SENT: "SMS sent successfully";
    readonly PUSH_NOTIFICATION_SENT: "Push notification sent successfully";
    readonly FILE_DOWNLOADED: "File downloaded successfully";
    readonly FILE_PROCESSED: "File processed successfully";
    readonly FILE_FORMAT_VALIDATED: "File format validated successfully";
    readonly SEARCH_COMPLETED: "Search completed successfully";
    readonly FILTER_APPLIED: "Filter applied successfully";
    readonly SORT_APPLIED: "Sort applied successfully";
};
export declare const HTTP_STATUS: {
    readonly OK: 200;
    readonly CREATED: 201;
    readonly ACCEPTED: 202;
    readonly NO_CONTENT: 204;
    readonly PARTIAL_CONTENT: 206;
    readonly MOVED_PERMANENTLY: 301;
    readonly FOUND: 302;
    readonly NOT_MODIFIED: 304;
    readonly TEMPORARY_REDIRECT: 307;
    readonly PERMANENT_REDIRECT: 308;
    readonly BAD_REQUEST: 400;
    readonly UNAUTHORIZED: 401;
    readonly PAYMENT_REQUIRED: 402;
    readonly FORBIDDEN: 403;
    readonly NOT_FOUND: 404;
    readonly METHOD_NOT_ALLOWED: 405;
    readonly NOT_ACCEPTABLE: 406;
    readonly REQUEST_TIMEOUT: 408;
    readonly CONFLICT: 409;
    readonly GONE: 410;
    readonly LENGTH_REQUIRED: 411;
    readonly PRECONDITION_FAILED: 412;
    readonly PAYLOAD_TOO_LARGE: 413;
    readonly URI_TOO_LONG: 414;
    readonly UNSUPPORTED_MEDIA_TYPE: 415;
    readonly RANGE_NOT_SATISFIABLE: 416;
    readonly EXPECTATION_FAILED: 417;
    readonly UNPROCESSABLE_ENTITY: 422;
    readonly TOO_EARLY: 425;
    readonly UPGRADE_REQUIRED: 426;
    readonly PRECONDITION_REQUIRED: 428;
    readonly TOO_MANY_REQUESTS: 429;
    readonly REQUEST_HEADER_FIELDS_TOO_LARGE: 431;
    readonly UNAVAILABLE_FOR_LEGAL_REASONS: 451;
    readonly INTERNAL_SERVER_ERROR: 500;
    readonly NOT_IMPLEMENTED: 501;
    readonly BAD_GATEWAY: 502;
    readonly SERVICE_UNAVAILABLE: 503;
    readonly GATEWAY_TIMEOUT: 504;
    readonly HTTP_VERSION_NOT_SUPPORTED: 505;
    readonly VARIANT_ALSO_NEGOTIATES: 506;
    readonly INSUFFICIENT_STORAGE: 507;
    readonly LOOP_DETECTED: 508;
    readonly NOT_EXTENDED: 510;
    readonly NETWORK_AUTHENTICATION_REQUIRED: 511;
};
export declare const RESPONSE_TEMPLATES: {
    readonly SUCCESS: (message: string, data?: any) => {
        success: boolean;
        message: string;
        data: any;
        timestamp: string;
    };
    readonly ERROR: (message: string, errors?: any[], statusCode?: number) => {
        success: boolean;
        message: string;
        errors: any[];
        statusCode: number;
        timestamp: string;
    };
    readonly PAGINATED: (data: any[], total: number, page: number, limit: number, message: string) => {
        success: boolean;
        message: string;
        data: any[];
        pagination: {
            total: number;
            totalPages: number;
            currentPage: number;
            pageSize: number;
            hasNext: boolean;
            hasPrev: boolean;
            nextPage: number | null;
            prevPage: number | null;
        };
        timestamp: string;
    };
    readonly HEALTH: (service: string, status: string, details?: any) => any;
};
export declare const VALIDATION_MESSAGES: {
    readonly REQUIRED: (field: string) => string;
    readonly MIN_LENGTH: (field: string, min: number) => string;
    readonly MAX_LENGTH: (field: string, max: number) => string;
    readonly INVALID_FORMAT: (field: string) => string;
    readonly INVALID_TYPE: (field: string, type: string) => string;
    readonly NOT_MATCH: (field1: string, field2: string) => string;
    readonly INVALID_VALUE: (field: string) => string;
    readonly UNIQUE: (field: string) => string;
    readonly NOT_FOUND: (field: string) => string;
    readonly INVALID_EMAIL: () => string;
    readonly INVALID_PHONE: () => string;
    readonly INVALID_PASSWORD: () => string;
    readonly INVALID_URL: () => string;
    readonly INVALID_DATE: () => string;
    readonly INVALID_BOOLEAN: () => string;
    readonly INVALID_NUMBER: () => string;
    readonly INVALID_ARRAY: () => string;
    readonly INVALID_OBJECT_ID: () => string;
    readonly INVALID_SLUG: () => string;
    readonly INVALID_FILE_TYPE: (allowedTypes: string[]) => string;
    readonly FILE_TOO_LARGE: (maxSizeMB: number) => string;
};
export declare const CATEGORY_MESSAGES: {
    readonly CREATED: "Category created successfully";
    readonly UPDATED: "Category updated successfully";
    readonly DELETED: "Category deleted successfully";
    readonly FETCHED: "Category fetched successfully";
    readonly LIST_FETCHED: "Categories fetched successfully";
    readonly TREE_FETCHED: "Category tree fetched successfully";
    readonly IMAGE_UPLOADED: "Category image uploaded successfully";
    readonly IMAGE_DELETED: "Category image deleted successfully";
    readonly STATUS_TOGGLED: "Category status toggled successfully";
    readonly FEATURED_TOGGLED: "Category featured status toggled successfully";
    readonly BULK_UPDATED: "Categories updated in bulk successfully";
    readonly BULK_DELETED: "Categories deleted in bulk successfully";
    readonly NOT_FOUND: "Category not found";
    readonly EXISTS: "Category already exists";
    readonly HAS_CHILDREN: "Cannot delete category with sub-categories";
    readonly INVALID_PARENT: "Invalid parent category";
    readonly SELF_PARENT: "Category cannot be its own parent";
    readonly INVALID_IMAGE: "Invalid category image";
    readonly IMAGE_NOT_FOUND: "Category image not found";
    readonly SLUG_EXISTS: "Category slug already exists";
    readonly NAME_REQUIRED: "Category name is required";
    readonly NAME_LENGTH: "Category name must be 2-100 characters";
    readonly DESCRIPTION_LENGTH: "Description cannot exceed 500 characters";
    readonly META_TITLE_LENGTH: "Meta title cannot exceed 100 characters";
    readonly META_DESC_LENGTH: "Meta description cannot exceed 200 characters";
    readonly SLUG_INVALID: "Invalid slug format";
};
export declare const UPLOAD_MESSAGES: {
    readonly URL_GENERATED: "Upload URL generated successfully";
    readonly BULK_URLS_GENERATED: "Bulk upload URLs generated successfully";
    readonly FILE_UPLOADED: "File uploaded successfully";
    readonly FILE_VALIDATED: "File validated successfully";
    readonly FILE_INFO_FETCHED: "File information fetched successfully";
    readonly FILE_DELETED: "File deleted successfully";
    readonly NO_FILE: "No file provided";
    readonly INVALID_TYPE: "Invalid file type";
    readonly TOO_LARGE: "File too large";
    readonly UPLOAD_FAILED: "File upload failed";
    readonly S3_ERROR: "S3 storage error";
    readonly NOT_FOUND: "File not found";
    readonly INVALID_KEY: "Invalid file key";
    readonly FILENAME_REQUIRED: "File name is required";
    readonly FILETYPE_REQUIRED: "File type is required";
    readonly FILES_ARRAY_REQUIRED: "Files array is required";
};
declare const _default: {
    ERROR_MESSAGES: {
        readonly NO_TOKEN: "Access denied. No token provided.";
        readonly INVALID_TOKEN: "Invalid or expired token.";
        readonly INVALID_ROLE: "Invalid user role.";
        readonly ACCESS_DENIED: "Access denied. Insufficient permissions.";
        readonly USER_NOT_FOUND: "User not found.";
        readonly ACCOUNT_INACTIVE: "Your account is inactive. Please contact support.";
        readonly EMAIL_NOT_VERIFIED: "Please verify your email address.";
        readonly PHONE_NOT_VERIFIED: "Please verify your phone number.";
        readonly INVALID_CREDENTIALS: "Invalid email/phone or password.";
        readonly ACCOUNT_LOCKED: "Account is temporarily locked. Try again later.";
        readonly SESSION_EXPIRED: "Session expired. Please try again.";
        readonly MAX_ATTEMPTS_EXCEEDED: "Maximum attempts exceeded. Please request new OTP.";
        readonly FILE_UPLOAD_FAILED: "File upload failed";
        readonly INVALID_FILE_TYPE: "Invalid file type. Allowed: JPEG, PNG, JPG, WebP, GIF, SVG";
        readonly FILE_TOO_LARGE: "File size too large. Maximum size: 10MB";
        readonly FILE_NOT_FOUND_IN_S3: "File not found in storage";
        readonly S3_CONFIGURATION_ERROR: "S3 storage not configured properly";
        readonly PRESIGNED_URL_GENERATION_FAILED: "Failed to generate upload URL";
        readonly BULK_UPLOAD_LIMIT_EXCEEDED: "Maximum 10 files allowed per bulk upload";
        readonly FILE_VALIDATION_FAILED: "File validation failed";
        readonly IMAGE_FOLDER_INVALID: "Image must be in category-images folder";
        readonly ORPHANED_IMAGES_CLEANUP_FAILED: "Failed to cleanup orphaned images";
        readonly VALIDATION_ERROR: "Validation failed.";
        readonly INVALID_EMAIL: "Invalid email format.";
        readonly INVALID_PHONE: "Invalid phone number. Must be 10 digits.";
        readonly INVALID_PASSWORD: "Password must be at least 6 characters.";
        readonly PASSWORDS_DONT_MATCH: "Passwords do not match.";
        readonly INVALID_NAME: "Name must be between 2 and 50 characters.";
        readonly INVALID_GENDER: "Gender must be male, female, or other.";
        readonly INVALID_DATE: "Invalid date format. Use YYYY-MM-DD.";
        readonly INVALID_OTP: "Invalid or expired OTP.";
        readonly INVALID_SESSION_ID: "Invalid session ID.";
        readonly IDENTIFIER_REQUIRED: "Email or phone is required.";
        readonly INVALID_IDENTIFIER: "Please enter a valid email or 10-digit phone number.";
        readonly INVALID_TYPE: "Invalid type. Must be register, login, or forgot_password.";
        readonly USER_DATA_INVALID: "userData must be an object.";
        readonly SESSION_ID_REQUIRED: "Session ID is required.";
        readonly OTP_REQUIRED: "OTP is required.";
        readonly OTP_INVALID_FORMAT: "OTP must be exactly 6 digits.";
        readonly OTP_NUMERIC: "OTP must contain only numbers.";
        readonly NAME_REQUIRED: "Name is required.";
        readonly PASSWORD_REQUIRED: "Password is required.";
        readonly PASSWORD_EMPTY: "Password cannot be empty.";
        readonly CONFIRM_PASSWORD_REQUIRED: "Confirm password is required.";
        readonly EMAIL_REQUIRED: "Email is required.";
        readonly GENDER_INVALID: "Gender must be male, female, or other.";
        readonly DATE_FORMAT_INVALID: "Invalid date format. Use YYYY-MM-DD.";
        readonly EMAIL_ALREADY_REGISTERED: "Email already registered";
        readonly PHONE_ALREADY_REGISTERED: "Phone number already registered";
        readonly INVALID_SESSION_TYPE_REGISTER: "Invalid session type for registration";
        readonly INVALID_SESSION_TYPE_PASSWORD_RESET: "Invalid session type for password reset";
        readonly SESSION_EXPIRED_NOT_VERIFIED: "Session expired or not verified";
        readonly REGISTRATION_IDENTIFIER_MISMATCH: "Registration identifier must match the identifier used for OTP verification";
        readonly PASSWORD_PREPARATION_FAILED: "Password validation failed";
        readonly PASSWORD_RESET_FAILED: "Password reset failed";
        readonly FORGOT_PASSWORD_OTP_MESSAGE: "If your account exists, you will receive an OTP.";
        readonly ACCOUNT_DEACTIVATED: "Account is deactivated. Please contact support.";
        readonly ACCOUNT_NOT_VERIFIED: "Account not verified. Please verify your account.";
        readonly NO_PASSWORD_FIELD: "No password field found in user object";
        readonly PASSWORD_NOT_HASHED: "Password not properly hashed";
        readonly NOT_FOUND: "Resource not found.";
        readonly ALREADY_EXISTS: "Resource already exists.";
        readonly INVALID_OBJECT_ID: "Invalid MongoDB ObjectId";
        readonly EMPTY_ARRAY_NOT_ALLOWED: "Array cannot be empty";
        readonly REQUIRED_PARAM_MISSING: "Required parameter is missing";
        readonly INVALID_PAGINATION_PARAMS: "Invalid pagination parameters";
        readonly CART_EMPTY: "Cart is empty.";
        readonly INVALID_QUANTITY: "Invalid quantity.";
        readonly ORDER_CANCELLED: "Order has been cancelled.";
        readonly SERVER_ERROR: "Internal server error.";
        readonly DATABASE_ERROR: "Database connection error.";
        readonly UPLOAD_ERROR: "File upload failed.";
        readonly EMAIL_SEND_ERROR: "Failed to send email.";
        readonly SMS_SEND_ERROR: "Failed to send SMS.";
        readonly AWS_S3_ERROR: "AWS S3 service error";
        readonly MONGOOSE_ERROR: "Database operation failed";
        readonly VALIDATION_MIDDLEWARE_ERROR: "Validation middleware error";
        readonly TOO_MANY_REQUESTS: "Too many requests. Please try again later.";
        readonly OPERATION_NOT_ALLOWED: "Operation not allowed";
        readonly INSUFFICIENT_PERMISSIONS: "Insufficient permissions for this operation";
        readonly FEATURE_NOT_IMPLEMENTED: "Feature not implemented yet";
        readonly SERVICE_UNAVAILABLE: "Service temporarily unavailable";
        readonly INVALID_SLUG_FORMAT: "Slug can only contain lowercase letters, numbers, and hyphens";
        readonly INVALID_BOOLEAN_VALUE: "Value must be true or false";
        readonly INVALID_NUMBER: "Invalid number format";
        readonly INVALID_ARRAY: "Invalid array format";
        readonly STRING_LENGTH_EXCEEDED: "String length exceeded maximum limit";
        readonly INVALID_URL_FORMAT: "Invalid URL format";
    };
    SUCCESS_MESSAGES: {
        readonly LOGIN_SUCCESS: "Login successful.";
        readonly REGISTER_SUCCESS: "Registration successful.";
        readonly LOGOUT_SUCCESS: "Logout successful.";
        readonly PASSWORD_RESET: "Password reset successful.";
        readonly EMAIL_VERIFIED: "Email verified successfully.";
        readonly PHONE_VERIFIED: "Phone verified successfully.";
        readonly PROFILE_UPDATED: "Profile updated successfully.";
        readonly OTP_SENT: "OTP sent successfully.";
        readonly OTP_VERIFIED: "OTP verified successfully.";
        readonly OTP_GENERATED_DEV: "OTP generated successfully (check server console)";
        readonly OTP_EMAIL_SENT: "OTP sent to your email";
        readonly OTP_EMAIL_ISSUE: "OTP generated (email service issue)";
        readonly OTP_SMS_NOT_CONFIGURED: "OTP would be sent to your phone (SMS service not configured)";
        readonly OTP_VERIFIED_DEV: "OTP verified successfully (Development Mode)";
        readonly WELCOME_EMAIL_SENT: "Welcome email sent";
        readonly TEST_USER_CREATED: "Test user created for development";
        readonly PASSWORD_UPDATED_RELOGIN: "Password updated. Please try login again.";
        readonly PASSWORD_REHASHED: "Password re-hashed and saved";
        readonly USER_REGISTERED_SUCCESS: "User registered successfully";
        readonly UPLOAD_URL_GENERATED: "Upload URL generated successfully";
        readonly BULK_UPLOAD_URLS_GENERATED: "Bulk upload URLs generated successfully";
        readonly IMAGE_UPLOADED: "Image uploaded successfully";
        readonly IMAGE_VALIDATED: "Image validated successfully";
        readonly IMAGE_INFO_FETCHED: "Image information fetched successfully";
        readonly IMAGE_DELETED: "Image deleted successfully";
        readonly S3_FILE_INFO_FETCHED: "File information fetched successfully";
        readonly PRESIGNED_URL_CREATED: "Presigned URL created successfully";
        readonly DOWNLOAD_URL_GENERATED: "Download URL generated successfully";
        readonly VIEW_URL_GENERATED: "View URL generated successfully";
        readonly FILE_EXISTS_CHECKED: "File existence checked successfully";
        readonly S3_OPERATION_SUCCESS: "S3 operation completed successfully";
        readonly SERVICE_ADDED: "Service created successfully";
        readonly SERVICE_UPDATED: "Service updated successfully.";
        readonly SERVICE_DELETED: "Service deleted successfully.";
        readonly SERVICE_FETCHED: "Service fetched successfully";
        readonly ADDED_TO_CART: "Product added to cart.";
        readonly CART_UPDATED: "Cart updated successfully.";
        readonly CART_CLEARED: "Cart cleared successfully.";
        readonly CART_FETCHED: "Cart fetched successfully";
        readonly ORDER_PLACED: "Order placed successfully.";
        readonly ORDER_UPDATED: "Order updated successfully.";
        readonly ORDER_CANCELLED: "Order cancelled successfully.";
        readonly ORDER_FETCHED: "Order fetched successfully";
        readonly ORDERS_FETCHED: "Orders fetched successfully";
        readonly REVIEW_ADDED: "Review added successfully.";
        readonly REVIEW_UPDATED: "Review updated successfully.";
        readonly REVIEW_DELETED: "Review deleted successfully.";
        readonly REVIEWS_FETCHED: "Reviews fetched successfully";
        readonly OPERATION_SUCCESS: "Operation completed successfully";
        readonly DATA_FETCHED: "Data fetched successfully";
        readonly DATA_UPDATED: "Data updated successfully";
        readonly DATA_DELETED: "Data deleted successfully";
        readonly DATA_CREATED: "Data created successfully";
        readonly BULK_OPERATION_SUCCESS: "Bulk operation completed successfully";
        readonly VALIDATION_SUCCESS: "Validation passed successfully";
        readonly HEALTH_CHECK_OK: "Service is operational";
        readonly CONFIGURATION_VALID: "Configuration is valid";
        readonly SETTINGS_UPDATED: "Settings updated successfully";
        readonly CACHE_CLEARED: "Cache cleared successfully";
        readonly PAGINATED_DATA_FETCHED: "Paginated data fetched successfully";
        readonly SYSTEM_HEALTHY: "System is healthy";
        readonly SERVICE_RUNNING: "Service is running normally";
        readonly BACKUP_CREATED: "Backup created successfully";
        readonly MAINTENANCE_COMPLETED: "Maintenance completed successfully";
        readonly API_REQUEST_SUCCESS: "API request successful";
        readonly WEBHOOK_RECEIVED: "Webhook received successfully";
        readonly INTEGRATION_SUCCESS: "Integration completed successfully";
        readonly NOTIFICATION_SENT: "Notification sent successfully";
        readonly EMAIL_SENT: "Email sent successfully";
        readonly SMS_SENT: "SMS sent successfully";
        readonly PUSH_NOTIFICATION_SENT: "Push notification sent successfully";
        readonly FILE_DOWNLOADED: "File downloaded successfully";
        readonly FILE_PROCESSED: "File processed successfully";
        readonly FILE_FORMAT_VALIDATED: "File format validated successfully";
        readonly SEARCH_COMPLETED: "Search completed successfully";
        readonly FILTER_APPLIED: "Filter applied successfully";
        readonly SORT_APPLIED: "Sort applied successfully";
    };
    HTTP_STATUS: {
        readonly OK: 200;
        readonly CREATED: 201;
        readonly ACCEPTED: 202;
        readonly NO_CONTENT: 204;
        readonly PARTIAL_CONTENT: 206;
        readonly MOVED_PERMANENTLY: 301;
        readonly FOUND: 302;
        readonly NOT_MODIFIED: 304;
        readonly TEMPORARY_REDIRECT: 307;
        readonly PERMANENT_REDIRECT: 308;
        readonly BAD_REQUEST: 400;
        readonly UNAUTHORIZED: 401;
        readonly PAYMENT_REQUIRED: 402;
        readonly FORBIDDEN: 403;
        readonly NOT_FOUND: 404;
        readonly METHOD_NOT_ALLOWED: 405;
        readonly NOT_ACCEPTABLE: 406;
        readonly REQUEST_TIMEOUT: 408;
        readonly CONFLICT: 409;
        readonly GONE: 410;
        readonly LENGTH_REQUIRED: 411;
        readonly PRECONDITION_FAILED: 412;
        readonly PAYLOAD_TOO_LARGE: 413;
        readonly URI_TOO_LONG: 414;
        readonly UNSUPPORTED_MEDIA_TYPE: 415;
        readonly RANGE_NOT_SATISFIABLE: 416;
        readonly EXPECTATION_FAILED: 417;
        readonly UNPROCESSABLE_ENTITY: 422;
        readonly TOO_EARLY: 425;
        readonly UPGRADE_REQUIRED: 426;
        readonly PRECONDITION_REQUIRED: 428;
        readonly TOO_MANY_REQUESTS: 429;
        readonly REQUEST_HEADER_FIELDS_TOO_LARGE: 431;
        readonly UNAVAILABLE_FOR_LEGAL_REASONS: 451;
        readonly INTERNAL_SERVER_ERROR: 500;
        readonly NOT_IMPLEMENTED: 501;
        readonly BAD_GATEWAY: 502;
        readonly SERVICE_UNAVAILABLE: 503;
        readonly GATEWAY_TIMEOUT: 504;
        readonly HTTP_VERSION_NOT_SUPPORTED: 505;
        readonly VARIANT_ALSO_NEGOTIATES: 506;
        readonly INSUFFICIENT_STORAGE: 507;
        readonly LOOP_DETECTED: 508;
        readonly NOT_EXTENDED: 510;
        readonly NETWORK_AUTHENTICATION_REQUIRED: 511;
    };
    RESPONSE_TEMPLATES: {
        readonly SUCCESS: (message: string, data?: any) => {
            success: boolean;
            message: string;
            data: any;
            timestamp: string;
        };
        readonly ERROR: (message: string, errors?: any[], statusCode?: number) => {
            success: boolean;
            message: string;
            errors: any[];
            statusCode: number;
            timestamp: string;
        };
        readonly PAGINATED: (data: any[], total: number, page: number, limit: number, message: string) => {
            success: boolean;
            message: string;
            data: any[];
            pagination: {
                total: number;
                totalPages: number;
                currentPage: number;
                pageSize: number;
                hasNext: boolean;
                hasPrev: boolean;
                nextPage: number | null;
                prevPage: number | null;
            };
            timestamp: string;
        };
        readonly HEALTH: (service: string, status: string, details?: any) => any;
    };
    VALIDATION_MESSAGES: {
        readonly REQUIRED: (field: string) => string;
        readonly MIN_LENGTH: (field: string, min: number) => string;
        readonly MAX_LENGTH: (field: string, max: number) => string;
        readonly INVALID_FORMAT: (field: string) => string;
        readonly INVALID_TYPE: (field: string, type: string) => string;
        readonly NOT_MATCH: (field1: string, field2: string) => string;
        readonly INVALID_VALUE: (field: string) => string;
        readonly UNIQUE: (field: string) => string;
        readonly NOT_FOUND: (field: string) => string;
        readonly INVALID_EMAIL: () => string;
        readonly INVALID_PHONE: () => string;
        readonly INVALID_PASSWORD: () => string;
        readonly INVALID_URL: () => string;
        readonly INVALID_DATE: () => string;
        readonly INVALID_BOOLEAN: () => string;
        readonly INVALID_NUMBER: () => string;
        readonly INVALID_ARRAY: () => string;
        readonly INVALID_OBJECT_ID: () => string;
        readonly INVALID_SLUG: () => string;
        readonly INVALID_FILE_TYPE: (allowedTypes: string[]) => string;
        readonly FILE_TOO_LARGE: (maxSizeMB: number) => string;
    };
    CATEGORY_MESSAGES: {
        readonly CREATED: "Category created successfully";
        readonly UPDATED: "Category updated successfully";
        readonly DELETED: "Category deleted successfully";
        readonly FETCHED: "Category fetched successfully";
        readonly LIST_FETCHED: "Categories fetched successfully";
        readonly TREE_FETCHED: "Category tree fetched successfully";
        readonly IMAGE_UPLOADED: "Category image uploaded successfully";
        readonly IMAGE_DELETED: "Category image deleted successfully";
        readonly STATUS_TOGGLED: "Category status toggled successfully";
        readonly FEATURED_TOGGLED: "Category featured status toggled successfully";
        readonly BULK_UPDATED: "Categories updated in bulk successfully";
        readonly BULK_DELETED: "Categories deleted in bulk successfully";
        readonly NOT_FOUND: "Category not found";
        readonly EXISTS: "Category already exists";
        readonly HAS_CHILDREN: "Cannot delete category with sub-categories";
        readonly INVALID_PARENT: "Invalid parent category";
        readonly SELF_PARENT: "Category cannot be its own parent";
        readonly INVALID_IMAGE: "Invalid category image";
        readonly IMAGE_NOT_FOUND: "Category image not found";
        readonly SLUG_EXISTS: "Category slug already exists";
        readonly NAME_REQUIRED: "Category name is required";
        readonly NAME_LENGTH: "Category name must be 2-100 characters";
        readonly DESCRIPTION_LENGTH: "Description cannot exceed 500 characters";
        readonly META_TITLE_LENGTH: "Meta title cannot exceed 100 characters";
        readonly META_DESC_LENGTH: "Meta description cannot exceed 200 characters";
        readonly SLUG_INVALID: "Invalid slug format";
    };
    UPLOAD_MESSAGES: {
        readonly URL_GENERATED: "Upload URL generated successfully";
        readonly BULK_URLS_GENERATED: "Bulk upload URLs generated successfully";
        readonly FILE_UPLOADED: "File uploaded successfully";
        readonly FILE_VALIDATED: "File validated successfully";
        readonly FILE_INFO_FETCHED: "File information fetched successfully";
        readonly FILE_DELETED: "File deleted successfully";
        readonly NO_FILE: "No file provided";
        readonly INVALID_TYPE: "Invalid file type";
        readonly TOO_LARGE: "File too large";
        readonly UPLOAD_FAILED: "File upload failed";
        readonly S3_ERROR: "S3 storage error";
        readonly NOT_FOUND: "File not found";
        readonly INVALID_KEY: "Invalid file key";
        readonly FILENAME_REQUIRED: "File name is required";
        readonly FILETYPE_REQUIRED: "File type is required";
        readonly FILES_ARRAY_REQUIRED: "Files array is required";
    };
};
export default _default;
//# sourceMappingURL=message.d.ts.map